name: Sign Decompiled APK

on:
  workflow_dispatch:
    inputs:
      config_b64:
        description: Base64 encoded config.json
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip jq xmlstarlet

      - name: Install Apktool
        run: |
          wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool
          wget https://github.com/iBotPeaches/Apktool/releases/download/v2.11.1/apktool_2.11.1.jar -O apktool.jar

          chmod +x apktool

          sudo mv apktool /usr/local/bin/
          sudo mv apktool.jar /usr/local/bin/

          apktool --version

      - name: Locate zipalign & apksigner
        run: |
          echo "$ANDROID_HOME/build-tools"

          BUILD_TOOLS=$(find "$ANDROID_HOME/build-tools" -maxdepth 1 -mindepth 1 | sort | tail -1)

          echo "BUILD_TOOLS=$BUILD_TOOLS" >> $GITHUB_ENV

          echo "$BUILD_TOOLS" >> $GITHUB_PATH

          zipalign -h
          apksigner version

      - name: Decompile APK
        run: |
          apktool d main_app.apk -o decompiled_app --force

      - name: Remove META-INF
        run: |
          rm -rf decompiled_app/original/META-INF || true
          rm -rf decompiled_app/META-INF || true

      - name: Inject config.json
        run: |
          mkdir -p decompiled_app/assets/flutter_assets/assets

          echo "${{ github.event.inputs.config_b64 }}" | base64 -d > decompiled_app/assets/flutter_assets/assets/config.json

          APP_TITLE=$(jq -r '.appTitle' decompiled_app/assets/flutter_assets/assets/config.json)
          LOAD_ASSET=$(jq -r '.loadAsset' decompiled_app/assets/flutter_assets/assets/config.json)

          echo "APP_TITLE=$APP_TITLE" >> $GITHUB_ENV
          echo "LOAD_ASSET=$LOAD_ASSET" >> $GITHUB_ENV

      - name: Download WebApp
        if: env.LOAD_ASSET != '0'
        run: |
          APP_ID=$(jq -r '.appID' decompiled_app/assets/flutter_assets/assets/config.json)

          curl -L -X POST "${{ secrets.DOWNLOAD_SITE }}" \
            -F "token=${{ secrets.UPLOAD_TOKEN }}" \
            -F "appID=$APP_ID" \
            -o webapp.zip

          if unzip -t webapp.zip >/dev/null 2>&1; then
            mkdir -p decompiled_app/assets/flutter_assets/assets/webapp
            unzip -o webapp.zip -d decompiled_app/assets/flutter_assets/assets/webapp
          else
            echo "No valid webapp zip."
          fi

      - name: Modify app label
        run: |
          xmlstarlet ed --inplace \
            -N android="http://schemas.android.com/apk/res/android" \
            -u "/manifest/application/@android:label" \
            -v "$APP_TITLE" \
            decompiled_app/AndroidManifest.xml

      - name: Rebuild APK
        run: |
          apktool b decompiled_app -o unsigned.apk

      - name: Zipalign
        run: |
          zipalign -p -f 4 unsigned.apk aligned.apk

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_B64 }}" | base64 -d > appvly.jks

      - name: Sign APK
        run: |
          apksigner sign \
            --ks appvly.jks \
            --ks-key-alias "${{ secrets.KEY_ALIAS }}" \
            --ks-pass pass:"${{ secrets.KEYSTORE_PASS }}" \
            --key-pass pass:"${{ secrets.KEY_PASS }}" \
            --out final.apk \
            aligned.apk

      - name: Verify Signature
        run: |
          apksigner verify final.apk

      - name: Upload APK
        run: |
          APP_ID=$(jq -r '.appID' decompiled_app/assets/flutter_assets/assets/config.json)

          curl -L -X POST "${{ secrets.UPLOAD_SITE }}" \
            -F "file=@final.apk" \
            -F "token=${{ secrets.UPLOAD_TOKEN }}" \
            -F "appID=$APP_ID"
